name: example
description: A simple example app for the sliding_up_panel package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

