name: sliding_up_panel
description: A draggable Flutter widget that makes implementing a SlidingUpPanel
  much easier!
version: 2.0.0+1
homepage: https://mankeli.co

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.11.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/sliding_up_panel/assets/arrow.riv
